//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int notification_id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> restaurant_id { get; set; }
        public Nullable<int> booking_id { get; set; }
        public Nullable<int> review_id { get; set; }
        public string type { get; set; }
        public string title { get; set; }
        public string message { get; set; }
        public string link { get; set; }
        public bool is_read { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual Bookings Bookings { get; set; }
        public virtual Restaurants Restaurants { get; set; }
        public virtual Reviews Reviews { get; set; }
        public virtual Users Users { get; set; }
    }
}
