//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerLeads
    {
        public int LeadId { get; set; }
        public string Email { get; set; }
        public string RestaurantName { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public int BranchCount { get; set; }
        public string ServiceTypes { get; set; }
        public string ServiceTypeOther { get; set; }
        public string ServiceDescription { get; set; }
        public string CuisineStyle { get; set; }
        public string SignatureDishes { get; set; }
        public string AverageBill { get; set; }
        public string AverageBillOther { get; set; }
        public int TotalSeats { get; set; }
        public string FloorCount { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public string OpeningTime { get; set; }
        public string ClosingTime { get; set; }
        public string SlowHours { get; set; }
        public string BusyHours { get; set; }
        public string PartnershipGoal { get; set; }
        public string ServicePackage { get; set; }
        public string ContactName { get; set; }
        public string ContactRole { get; set; }
        public string ContactPhone { get; set; }
        public string Website { get; set; }
        public string SpaceDescription { get; set; }
        public string SeatingType { get; set; }
        public string PrivateRoomCount { get; set; }
        public string Amenities { get; set; }
        public string AmenitiesOther { get; set; }
        public string NearbyLandmark { get; set; }
        public string PhotoLink { get; set; }
        public string PreviousPartnership { get; set; }
        public string PreviousPartnershipOther { get; set; }
        public string PreviousPartnershipName { get; set; }
        public string Questions { get; set; }
        public System.DateTime SubmittedDate { get; set; }
        public string Status { get; set; }
    }
}
