//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestaurantImages
    {
        public int image_id { get; set; }
        public int restaurant_id { get; set; }
        public string image_url { get; set; }
        public string description { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
    }
}
