//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewReporting
    {
        public int report_id { get; set; }
        public int review_id { get; set; }
        public int reported_by_user_id { get; set; }
        public string report_type { get; set; }
        public string report_reason { get; set; }
        public string status { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> resolved_at { get; set; }
        public string resolved_by { get; set; }
    
        public virtual Reviews Reviews { get; set; }
        public virtual Users Users { get; set; }
    }
}
