//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartTable.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tables
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tables()
        {
            this.Bookings = new HashSet<Bookings>();
        }
    
        public int table_id { get; set; }
        public Nullable<int> restaurant_id { get; set; }
        public string table_number { get; set; }
        public Nullable<int> capacity { get; set; }
        public string type { get; set; }
        public Nullable<bool> is_available { get; set; }
    
        public virtual Restaurants Restaurants { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bookings> Bookings { get; set; }
    }
}
